@startuml ReAct_Pattern_Sequence
title ReAct pattern sequence diagram

skinparam responseMessageBelowArrow true
skinparam sequenceMessageAlign center
participant "User" as U #efbbff
participant "ReAct AI Agent" as RA #48D1CC
participant "LLM" as LLM #FFB347
participant Tools as T #87CEEB

U -> RA : Submit question

RA -> LLM : Process question

loop Process steps
    LLM --> RA : "🤔 Think"

    LLM --> RA : "Decide action or final answer"

    alt Action required
        break Error occurred
           RA -> T : 🎯 Execute action
        end

        T --> RA : 👀 Observation

        RA -> LLM : Process observation

    else Final Answer
        break Final Answer
            LLM --> RA : Final answer
        end
    end
end

RA -> U : Display final answer

@enduml
